"""Built-in exercise library. This file is the source of truth: startup re-syncs these rows.

Every entry carries complete metadata (see `X`). Rep ranges are reps, or seconds for timed exercises.
Equipment lists are ALL-required; an empty list means no equipment. `bodyweight` is never listed.
"""
from app.models.enums import ExerciseType as T
from app.models.enums import ExperienceLevel as L
from app.models.enums import MovementPattern as M

_ORDER = [L.beginner, L.intermediate, L.advanced]


def X(name, primary, secondary, pattern, etype, diff, gear, reps, sets, description, how,
      *, min_level=None, timed=False, compound=None):
    if min_level is None:  # advanced moves are still open to intermediates by default
        min_level = diff if diff != L.advanced else L.intermediate
    if compound is None:
        compound = etype in (T.compound, T.plyometric)
    return {
        "name": name, "primary": primary, "secondary": secondary, "pattern": pattern,
        "type": etype, "difficulty": diff, "min_level": min_level, "equipment": gear,
        "rep_min": reps[0], "rep_max": reps[1], "sets": sets, "description": description,
        "instructions": how, "is_compound": compound, "is_timed": timed,
    }


B, I, A = L.beginner, L.intermediate, L.advanced
C, ISO, CARDIO, PLYO = T.compound, T.isolation, T.cardio, T.plyometric

EXERCISE_LIBRARY = [
    # ---------------- chest ----------------
    X("Push-up", "chest", ["triceps", "shoulders", "core"], M.push, C, B, [], (8, 20), 3,
      "The foundational bodyweight press for chest, shoulders and triceps.",
      "Hands under shoulders, body in a straight line, lower your chest to the floor and press back up."),
    X("Incline push-up", "chest", ["triceps", "shoulders"], M.push, C, B, [], (10, 20), 3,
      "An easier push-up with the hands raised, ideal for building up to full push-ups.",
      "Place your hands on a sturdy raised surface, keep your body straight, lower your chest to it and press away."),
    X("Dumbbell bench press", "chest", ["triceps", "shoulders"], M.push, C, B, ["dumbbells", "bench"], (8, 12), 3,
      "A free-weight chest press that lets each arm work independently.",
      "Lie on the bench, lower the dumbbells to chest level with elbows about 45 degrees, then press up."),
    X("Barbell bench press", "chest", ["triceps", "shoulders"], M.push, C, I, ["barbell", "bench"], (5, 8), 4,
      "The classic heavy chest press and a core strength lift.",
      "Lower the bar to mid-chest under control with shoulder blades pinched back, then press it up."),
    X("Incline dumbbell press", "chest", ["shoulders", "triceps"], M.push, C, B, ["dumbbells", "bench"], (8, 12), 3,
      "Emphasises the upper chest using an inclined bench.",
      "Set the bench to a low incline, press the dumbbells from chest height to above your upper chest, then lower slowly."),
    X("Machine chest press", "chest", ["triceps", "shoulders"], M.push, C, B, ["machines"], (8, 12), 3,
      "A guided chest press that is easy to learn and safe to push hard.",
      "Adjust the seat so handles are at mid-chest, press forward until arms are nearly straight, then return slowly."),
    X("Resistance band chest press", "chest", ["triceps", "shoulders"], M.push, C, B, ["resistance_bands"], (10, 15), 3,
      "A press you can do anywhere with a band anchored behind you.",
      "Anchor the band behind you at chest height, hold the ends at your chest and press forward until arms are straight."),
    X("Dumbbell fly", "chest", ["shoulders"], M.other, ISO, B, ["dumbbells", "bench"], (10, 15), 3,
      "An isolation move that stretches and squeezes the chest.",
      "Lie on the bench with dumbbells above your chest, open your arms in a wide arc with soft elbows, then bring them back together."),
    X("Cable crossover", "chest", ["shoulders"], M.other, ISO, I, ["cable_machine"], (12, 15), 3,
      "Constant-tension chest isolation using two high cables.",
      "Set pulleys high, step forward with a slight lean, and sweep the handles down and together in front of your hips."),
    X("Pec deck", "chest", ["shoulders"], M.other, ISO, B, ["machines"], (10, 15), 3,
      "A guided machine fly that isolates the chest.",
      "Sit with your back flat, bring the pads together in front of you by squeezing your chest, then open slowly."),
    # ---------------- back ----------------
    X("Pull-up", "back", ["biceps", "forearms"], M.pull, C, I, ["pull_up_bar"], (5, 10), 3,
      "The benchmark bodyweight pull for lats and upper back.",
      "From a dead hang, pull your chest toward the bar, then lower with control."),
    X("Chin-up", "back", ["biceps", "forearms"], M.pull, C, I, ["pull_up_bar"], (5, 10), 3,
      "An underhand pull-up that brings the biceps in strongly.",
      "Hang with an underhand grip, pull your chin over the bar, then lower fully."),
    X("Assisted pulldown machine", "back", ["biceps"], M.pull, C, B, ["machines"], (6, 10), 3,
      "Builds toward unassisted pull-ups by offsetting some of your bodyweight.",
      "Kneel on the pad, grip the handles, pull your chest to the bar, and lower under control."),
    X("Lat pulldown", "back", ["biceps"], M.pull, C, B, ["cable_machine"], (8, 12), 3,
      "A vertical pull that targets the lats and is easy to scale.",
      "Pull the bar to your upper chest by driving your elbows down, then return slowly."),
    X("Seated cable row", "back", ["biceps"], M.pull, C, B, ["cable_machine"], (8, 12), 3,
      "A horizontal pull for mid-back thickness.",
      "Sit tall, pull the handle to your waist by squeezing your shoulder blades, then extend."),
    X("Seated machine row", "back", ["biceps"], M.pull, C, B, ["machines"], (8, 12), 3,
      "A chest-supported row that takes the lower back out of the equation.",
      "Press your chest into the pad, row the handles back past your ribs, then extend slowly."),
    X("One-arm dumbbell row", "back", ["biceps"], M.pull, C, B, ["dumbbells"], (8, 12), 3,
      "A simple unilateral row you can do with a single dumbbell.",
      "Support yourself with one hand, row the dumbbell to your hip, and lower it fully."),
    X("Chest-supported dumbbell row", "back", ["biceps", "shoulders"], M.pull, C, B, ["dumbbells", "bench"], (8, 12), 3,
      "A strict row with the chest on an incline bench to remove momentum.",
      "Lie face down on an inclined bench, row both dumbbells toward your hips, and lower with control."),
    X("Barbell row", "back", ["biceps", "forearms"], M.pull, C, I, ["barbell"], (6, 10), 3,
      "A heavy bent-over row for back strength and size.",
      "Hinge forward with a flat back and row the bar to your lower ribs."),
    X("Resistance band row", "back", ["biceps"], M.pull, C, B, ["resistance_bands"], (10, 15), 3,
      "A row you can do anywhere with a band anchored in front of you.",
      "Anchor the band at chest height, sit or stand tall, and pull the handles to your ribs squeezing your shoulder blades."),
    X("Band lat pulldown", "back", ["biceps"], M.pull, C, B, ["resistance_bands", "pull_up_bar"], (10, 15), 3,
      "A home version of the lat pulldown using a band looped over a bar.",
      "Loop the band over the bar, kneel below it, and pull the ends down to your chest by driving your elbows to your sides."),
    X("Superman", "back", ["glutes"], M.other, ISO, B, [], (10, 15), 3,
      "A floor exercise for the lower back and the muscles along the spine.",
      "Lie face down with arms extended, lift your arms, chest and legs off the floor, pause, and lower."),
    X("Prone Y raise", "back", ["shoulders"], M.pull, ISO, B, [], (10, 15), 3,
      "Targets the lower traps and rear shoulders with no equipment.",
      "Lie face down with arms overhead in a Y, lift your arms off the floor with thumbs up, pause, and lower."),
    X("Straight-arm pulldown", "back", ["core"], M.pull, ISO, B, ["cable_machine"], (10, 15), 3,
      "Isolates the lats without the biceps taking over.",
      "With straight arms, push the bar from head height down to your thighs, then return slowly."),
    X("Dumbbell shrug", "back", ["forearms"], M.other, ISO, B, ["dumbbells"], (10, 15), 3,
      "Builds the upper trapezius.",
      "Hold dumbbells at your sides, lift your shoulders straight up toward your ears, pause, and lower."),
    # ---------------- shoulders ----------------
    X("Dumbbell shoulder press", "shoulders", ["triceps"], M.push, C, B, ["dumbbells"], (8, 12), 3,
      "A free-weight overhead press for the shoulders.",
      "Press the dumbbells from shoulder height to overhead without arching your lower back."),
    X("Overhead press", "shoulders", ["triceps", "core"], M.push, C, I, ["barbell"], (5, 8), 4,
      "The standing barbell press, a classic upper-body strength lift.",
      "Brace, press the bar from your collarbone to overhead, and move your head through at the top."),
    X("Machine shoulder press", "shoulders", ["triceps"], M.push, C, B, ["machines"], (8, 12), 3,
      "A guided overhead press that is easy to load safely.",
      "Adjust the seat so handles are at shoulder height, press overhead, and lower slowly."),
    X("Arnold press", "shoulders", ["triceps"], M.push, C, I, ["dumbbells"], (8, 12), 3,
      "A rotating dumbbell press that works all three shoulder heads.",
      "Start with palms facing you at chest height, rotate your palms outward as you press overhead, and reverse on the way down."),
    X("Pike push-up", "shoulders", ["triceps", "chest"], M.push, C, I, [], (6, 12), 3,
      "A bodyweight shoulder press with hips high.",
      "From a push-up position, walk your feet in so your hips point up, lower your head toward the floor, and press back."),
    X("Resistance band shoulder press", "shoulders", ["triceps"], M.push, C, B, ["resistance_bands"], (10, 15), 3,
      "An overhead press using a band under your feet.",
      "Stand on the band, hold the ends at shoulder height, and press overhead until your arms are straight."),
    X("Dumbbell lateral raise", "shoulders", [], M.other, ISO, B, ["dumbbells"], (12, 20), 3,
      "Builds the side of the shoulder for width.",
      "With a slight elbow bend, raise the dumbbells out to shoulder height and lower slowly."),
    X("Cable lateral raise", "shoulders", [], M.other, ISO, I, ["cable_machine"], (12, 20), 3,
      "Lateral raise with constant cable tension.",
      "Stand side-on to a low pulley, raise your arm out to shoulder height, and lower slowly."),
    X("Resistance band lateral raise", "shoulders", [], M.other, ISO, B, ["resistance_bands"], (12, 20), 3,
      "A portable way to train the side delts.",
      "Stand on the band, hold the ends, and raise your arms out to shoulder height with soft elbows."),
    X("Rear delt fly", "shoulders", ["back"], M.pull, ISO, B, ["dumbbells"], (12, 20), 3,
      "Targets the rear shoulders, which help posture and balance pressing work.",
      "Hinge forward with a flat back, raise the dumbbells out to the sides with soft elbows, and lower slowly."),
    X("Face pull", "shoulders", ["back"], M.pull, ISO, B, ["cable_machine"], (12, 20), 3,
      "Strengthens the rear delts and upper back, good for shoulder health.",
      "Set the rope at face height, pull it toward your forehead with elbows high, and squeeze before returning."),
    X("Reverse pec deck", "shoulders", ["back"], M.pull, ISO, B, ["machines"], (12, 20), 3,
      "A guided rear-delt fly on the pec deck.",
      "Face the pad, grip the handles, and sweep your arms back and out until in line with your shoulders."),
    X("Resistance band pull-apart", "shoulders", ["back"], M.pull, ISO, B, ["resistance_bands"], (12, 20), 3,
      "A simple band move for the rear delts and upper back.",
      "Hold the band at chest height and pull it apart until your arms form a T, then return slowly."),
    X("Reverse snow angel", "shoulders", ["back"], M.pull, ISO, B, [], (10, 15), 3,
      "A floor move for the rear shoulders and upper back that needs no equipment.",
      "Lie face down with arms by your sides, sweep your arms in a wide arc overhead keeping them off the floor, then return."),
    # ---------------- biceps ----------------
    X("Dumbbell biceps curl", "biceps", ["forearms"], M.other, ISO, B, ["dumbbells"], (8, 12), 3,
      "The standard biceps builder.",
      "Keep elbows at your sides, curl the dumbbells up, and lower them slowly."),
    X("Hammer curl", "biceps", ["forearms"], M.other, ISO, B, ["dumbbells"], (8, 12), 3,
      "A neutral-grip curl that also works the forearms.",
      "Hold dumbbells with palms facing each other, curl up without rotating your wrists, and lower slowly."),
    X("Incline dumbbell curl", "biceps", [], M.other, ISO, I, ["dumbbells", "bench"], (10, 15), 3,
      "Stretches the biceps under load on an inclined bench.",
      "Sit back on an incline bench with arms hanging, curl the dumbbells up, and lower fully."),
    X("Barbell curl", "biceps", ["forearms"], M.other, ISO, B, ["barbell"], (8, 12), 3,
      "A heavy two-arm biceps curl.",
      "Stand tall, curl the bar to shoulder height without swinging, and lower under control."),
    X("Cable biceps curl", "biceps", ["forearms"], M.other, ISO, B, ["cable_machine"], (10, 15), 3,
      "A curl with constant cable tension.",
      "Stand facing a low pulley, curl the handle up keeping elbows still, and lower slowly."),
    X("Resistance band curl", "biceps", ["forearms"], M.other, ISO, B, ["resistance_bands"], (12, 20), 3,
      "A portable biceps curl.",
      "Stand on the band, curl the ends up with elbows at your sides, and lower slowly."),
    X("Preacher curl machine", "biceps", [], M.other, ISO, B, ["machines"], (8, 12), 3,
      "A supported curl that keeps the upper arm fixed.",
      "Rest your upper arms on the pad, curl the handles up, and lower until your arms are nearly straight."),
    # ---------------- triceps ----------------
    X("Cable triceps pushdown", "triceps", [], M.other, ISO, B, ["cable_machine"], (10, 15), 3,
      "A staple triceps isolation exercise.",
      "Elbows pinned at your sides, press the handle down until your arms are straight, then return."),
    X("Overhead dumbbell triceps extension", "triceps", [], M.other, ISO, B, ["dumbbells"], (10, 15), 3,
      "Stretches the long head of the triceps.",
      "Hold one dumbbell overhead with both hands, lower it behind your head by bending your elbows, and extend."),
    X("Skull crusher", "triceps", [], M.other, ISO, I, ["barbell", "bench"], (8, 12), 3,
      "A lying triceps extension for mass.",
      "Lie on the bench with the bar above your chest, bend your elbows to lower it toward your forehead, then extend."),
    X("Bench dip", "triceps", ["chest", "shoulders"], M.push, C, B, ["bench"], (8, 15), 3,
      "A bodyweight triceps exercise using a bench or chair.",
      "Hands on the edge of a bench behind you, lower your hips by bending your elbows to about 90 degrees, then press up."),
    X("Close-grip bench press", "triceps", ["chest", "shoulders"], M.push, C, I, ["barbell", "bench"], (6, 10), 3,
      "A barbell press that shifts the load toward the triceps.",
      "Grip the bar shoulder-width, lower it to your lower chest with elbows tucked, and press up."),
    X("Diamond push-up", "triceps", ["chest", "shoulders"], M.push, C, I, [], (8, 15), 3,
      "A close-hand push-up that emphasises the triceps.",
      "Make a diamond with your hands under your chest, lower with elbows close to your body, and press up."),
    X("Resistance band triceps pushdown", "triceps", [], M.other, ISO, B, ["resistance_bands"], (12, 20), 3,
      "A band version of the pushdown.",
      "Anchor the band overhead, pin your elbows at your sides, and press down until your arms are straight."),
    X("Dumbbell triceps kickback", "triceps", [], M.other, ISO, B, ["dumbbells"], (10, 15), 3,
      "Isolates the triceps at full contraction.",
      "Hinge forward with your upper arm parallel to the floor, extend your elbow to straighten your arm, and return slowly."),
    # ---------------- forearms ----------------
    X("Wrist curl", "forearms", [], M.other, ISO, B, ["dumbbells"], (12, 20), 3,
      "Builds forearm and grip strength.",
      "Rest your forearms on your thighs palms up, curl the dumbbells with your wrists only, and lower slowly."),
    X("Farmer's carry", "forearms", ["core", "shoulders"], M.carry, C, B, ["dumbbells"], (30, 60), 3,
      "Walk with heavy weights to build grip, core and posture.",
      "Hold a heavy dumbbell in each hand, stand tall with shoulders back, and walk with short controlled steps for the set time.",
      timed=True),
    # ---------------- quads ----------------
    X("Bodyweight squat", "quads", ["glutes"], M.squat, C, B, [], (10, 20), 3,
      "The foundation squat pattern with no load.",
      "Stand shoulder-width apart, sit your hips back and down until your thighs are parallel, then stand up."),
    X("Goblet squat", "quads", ["glutes", "core"], M.squat, C, B, ["dumbbells"], (8, 15), 3,
      "A beginner-friendly loaded squat that teaches an upright torso.",
      "Hold one dumbbell at your chest, squat between your hips keeping your chest tall, then stand."),
    X("Kettlebell goblet squat", "quads", ["glutes", "core"], M.squat, C, B, ["kettlebell"], (8, 15), 3,
      "A goblet squat holding a kettlebell by the horns.",
      "Hold the kettlebell against your chest, squat down between your hips with a tall chest, then stand."),
    X("Barbell back squat", "quads", ["glutes", "core", "hamstrings"], M.squat, C, I, ["barbell", "squat_rack"], (5, 8), 4,
      "The king of leg exercises for strength and size.",
      "Set the bar on your upper back, brace, squat to parallel or below, and drive up through mid-foot."),
    X("Leg press", "quads", ["glutes", "hamstrings"], M.squat, C, B, ["machines"], (8, 15), 3,
      "A machine squat pattern that lets you load the legs heavily and safely.",
      "Place feet shoulder-width on the platform, lower until knees reach about 90 degrees, then press."),
    X("Hack squat", "quads", ["glutes"], M.squat, C, I, ["machines"], (8, 12), 3,
      "A machine squat that keeps the torso supported and the quads working hard.",
      "Stand on the platform with your back on the pad, lower until your thighs are parallel, then drive up."),
    X("Resistance band squat", "quads", ["glutes"], M.squat, C, B, ["resistance_bands"], (12, 20), 3,
      "A squat with added band resistance.",
      "Stand on the band with the ends at your shoulders, squat to parallel, then stand against the band's tension."),
    X("Walking lunge", "quads", ["glutes", "hamstrings"], M.lunge, C, B, [], (10, 20), 3,
      "A moving single-leg exercise for legs and balance.",
      "Step forward, lower your back knee toward the floor, then drive through the front foot into the next step."),
    X("Dumbbell lunge", "quads", ["glutes", "hamstrings"], M.lunge, C, B, ["dumbbells"], (8, 12), 3,
      "A loaded lunge for leg strength.",
      "Holding dumbbells at your sides, step forward, lower your back knee toward the floor, and push back to start."),
    X("Bulgarian split squat", "quads", ["glutes", "hamstrings"], M.lunge, C, I, ["dumbbells", "bench"], (8, 12), 3,
      "A demanding single-leg squat with the rear foot raised.",
      "Rest your back foot on a bench, lower your back knee toward the floor with the dumbbells at your sides, and stand."),
    X("Dumbbell step-up", "quads", ["glutes"], M.lunge, C, B, ["dumbbells", "bench"], (8, 12), 3,
      "A functional single-leg move onto a bench.",
      "Step onto the bench with one foot, drive through that heel to stand tall, and lower with control."),
    X("Leg extension", "quads", [], M.other, ISO, B, ["machines"], (10, 15), 3,
      "Isolates the quadriceps.",
      "Sit with the pad on your lower shins, extend your knees until your legs are straight, and lower slowly."),
    X("Wall sit", "quads", ["glutes"], M.squat, ISO, B, [], (30, 60), 3,
      "An isometric hold that builds quad endurance.",
      "Slide down a wall until your thighs are parallel to the floor and hold the position.",
      timed=True),
    # ---------------- hamstrings ----------------
    X("Dumbbell Romanian deadlift", "hamstrings", ["glutes", "back"], M.hinge, C, B, ["dumbbells"], (8, 12), 3,
      "A hip hinge that loads the hamstrings and glutes.",
      "With soft knees, push your hips back and slide the dumbbells down your thighs, then stand tall."),
    X("Romanian deadlift", "hamstrings", ["glutes", "back"], M.hinge, C, I, ["barbell"], (6, 10), 3,
      "The barbell hip hinge for hamstring and glute strength.",
      "Hold the bar at hip height, hinge back with a flat spine until hamstrings stretch, then stand."),
    X("Conventional deadlift", "hamstrings", ["glutes", "back", "forearms", "core"], M.hinge, C, A, ["barbell"], (3, 6), 3,
      "A full-body pull from the floor and a pillar of strength training.",
      "Set the bar over mid-foot, brace with a flat back, push the floor away and stand tall, then lower with control.",
      min_level=I),
    X("Kettlebell Romanian deadlift", "hamstrings", ["glutes", "back"], M.hinge, C, B, ["kettlebell"], (8, 12), 3,
      "A hip hinge with a kettlebell.",
      "Hold the kettlebell in both hands, push your hips back with soft knees until your hamstrings stretch, and stand."),
    X("Single-leg Romanian deadlift", "hamstrings", ["glutes", "core"], M.hinge, C, I, [], (8, 12), 3,
      "A balance-demanding hinge that needs no equipment.",
      "Stand on one leg, hinge forward as your other leg extends behind you, then return to standing."),
    X("Resistance band good morning", "hamstrings", ["glutes", "back"], M.hinge, C, B, ["resistance_bands"], (12, 20), 3,
      "A light hip hinge that teaches the movement.",
      "Stand on the band with it across your shoulders, push your hips back with a flat back, and stand tall."),
    X("Lying leg curl", "hamstrings", [], M.other, ISO, B, ["machines"], (10, 15), 3,
      "Isolates the hamstrings.",
      "Lie face down with the pad above your heels, curl your heels toward your glutes, and lower slowly."),
    # ---------------- glutes ----------------
    X("Glute bridge", "glutes", ["hamstrings", "core"], M.hinge, C, B, [], (10, 20), 3,
      "A simple floor exercise that wakes up and strengthens the glutes.",
      "Lie on your back with knees bent, push through your heels to lift your hips, squeeze, and lower."),
    X("Single-leg glute bridge", "glutes", ["hamstrings", "core"], M.hinge, C, I, [], (8, 15), 3,
      "A harder, unilateral glute bridge.",
      "Lie on your back with one foot planted and the other leg lifted, drive your hips up, squeeze, and lower."),
    X("Barbell hip thrust", "glutes", ["hamstrings"], M.hinge, C, I, ["barbell", "bench"], (6, 12), 3,
      "The most direct heavy glute builder.",
      "Rest your upper back on a bench with the bar across your hips, drive your hips up until your torso is flat, and lower."),
    X("Dumbbell hip thrust", "glutes", ["hamstrings"], M.hinge, C, B, ["dumbbells", "bench"], (8, 15), 3,
      "A hip thrust with a dumbbell, easy to set up.",
      "Rest your upper back on a bench with a dumbbell on your hips, thrust up until your torso is flat, and lower."),
    X("Kettlebell swing", "glutes", ["hamstrings", "core", "back"], M.hinge, C, I, ["kettlebell"], (10, 20), 3,
      "An explosive hip hinge that builds power and conditioning.",
      "Hinge back, snap your hips forward to swing the kettlebell to chest height, and let it fall back."),
    X("Cable pull-through", "glutes", ["hamstrings"], M.hinge, C, B, ["cable_machine"], (10, 15), 3,
      "A cable hinge that teaches hip drive.",
      "Face away from a low pulley with the rope between your legs, hinge back, then drive your hips forward to stand."),
    X("Cable glute kickback", "glutes", ["hamstrings"], M.other, ISO, B, ["cable_machine"], (10, 15), 3,
      "Isolates the glutes with constant tension.",
      "Attach an ankle strap, hinge slightly, and kick your leg straight back, squeezing your glute."),
    X("Donkey kick", "glutes", ["hamstrings"], M.other, ISO, B, [], (12, 20), 3,
      "A bodyweight glute isolation from all fours.",
      "From hands and knees, lift one leg back and up with a bent knee, squeeze, and lower."),
    X("Banded lateral walk", "glutes", [], M.other, ISO, B, ["resistance_bands"], (10, 20), 3,
      "Strengthens the outer glutes and hips.",
      "Place a band around your thighs, sit into a quarter squat, and step sideways keeping tension on the band."),
    # ---------------- calves ----------------
    X("Calf raise", "calves", [], M.other, ISO, B, [], (12, 25), 3,
      "A basic calf builder you can do anywhere.",
      "Stand on the balls of your feet, rise as high as you can, pause, and lower slowly."),
    X("Dumbbell calf raise", "calves", ["forearms"], M.other, ISO, B, ["dumbbells"], (12, 20), 3,
      "A loaded calf raise.",
      "Hold dumbbells at your sides, rise onto your toes, pause at the top, and lower slowly."),
    X("Standing calf raise machine", "calves", [], M.other, ISO, B, ["machines"], (10, 15), 3,
      "A machine calf raise that lets you load heavily.",
      "Place your shoulders under the pads, rise onto the balls of your feet, and lower for a deep stretch."),
    # ---------------- core ----------------
    X("Plank", "core", ["shoulders"], M.core, ISO, B, [], (30, 60), 3,
      "The standard isometric core hold.",
      "Forearms down, body in a straight line, brace your abs and hold.",
      timed=True),
    X("Side plank", "core", ["shoulders", "glutes"], M.core, ISO, B, [], (20, 45), 3,
      "Targets the obliques and the sides of the trunk.",
      "Lie on your side propped on your forearm, lift your hips so your body is straight, and hold. Repeat on the other side.",
      timed=True),
    X("Dead bug", "core", [], M.core, ISO, B, [], (8, 12), 3,
      "A controlled core move that protects the lower back.",
      "Lie on your back with arms up and knees at 90 degrees, extend the opposite arm and leg while keeping your back flat, then switch."),
    X("Crunch", "core", [], M.core, ISO, B, [], (12, 20), 3,
      "A basic abdominal flexion exercise.",
      "Lie on your back with knees bent, curl your shoulders off the floor, and lower with control."),
    X("Bicycle crunch", "core", [], M.core, ISO, B, [], (12, 24), 3,
      "Works the abs and obliques with a rotating motion.",
      "Lie on your back, bring opposite elbow and knee together while extending the other leg, and alternate."),
    X("Bird dog", "core", ["glutes", "back"], M.core, ISO, B, [], (8, 12), 3,
      "Builds trunk stability and coordination.",
      "From hands and knees, extend the opposite arm and leg, hold briefly without rotating, and switch."),
    X("Hanging knee raise", "core", ["forearms"], M.core, ISO, I, ["pull_up_bar"], (8, 15), 3,
      "A hanging ab exercise that is easier than the straight-leg version.",
      "Hang from the bar and lift your knees toward your chest without swinging."),
    X("Hanging leg raise", "core", ["forearms"], M.core, ISO, A, ["pull_up_bar"], (6, 12), 3,
      "An advanced hanging core exercise.",
      "Hang from the bar and raise straight legs until they reach about hip height, then lower slowly."),
    X("Cable crunch", "core", [], M.core, ISO, B, ["cable_machine"], (10, 15), 3,
      "A weighted ab crunch.",
      "Kneel below a high pulley holding the rope at your head, curl your ribs toward your hips, and return."),
    X("Russian twist", "core", [], M.rotation, ISO, B, [], (12, 24), 3,
      "A rotational exercise for the obliques.",
      "Sit leaning back with feet raised or on the floor, rotate your torso to tap the floor each side."),
    X("Pallof press", "core", ["shoulders"], M.rotation, ISO, B, ["resistance_bands"], (10, 15), 3,
      "Trains the core to resist rotation.",
      "Stand side-on to an anchored band, press your hands straight out from your chest, hold, and return without twisting."),
    # ---------------- conditioning (timed, no equipment) ----------------
    X("Burpee", "full_body", [], M.other, PLYO, I, [], (30, 45), 3,
      "A full-body conditioning move that raises your heart rate fast.",
      "Drop to a push-up, jump your feet in, then jump up with arms overhead.",
      timed=True),
    X("Jumping jack", "full_body", [], M.other, CARDIO, B, [], (30, 60), 3,
      "A classic low-skill cardio exercise.",
      "Jump your feet out while raising your arms overhead, then jump back to the start.",
      timed=True, compound=True),
    X("High knees", "full_body", ["quads", "core"], M.other, CARDIO, B, [], (30, 45), 3,
      "Running in place with the knees driven high.",
      "Run on the spot, driving your knees to hip height and pumping your arms.",
      timed=True, compound=True),
    X("Mountain climber", "full_body", ["core", "shoulders"], M.other, CARDIO, B, [], (30, 45), 3,
      "A cardio exercise from the plank position.",
      "From a high plank, drive your knees alternately toward your chest at a steady pace.",
      timed=True, compound=True),
    X("Squat jump", "full_body", ["quads", "glutes", "calves"], M.squat, PLYO, I, [], (30, 45), 3,
      "An explosive squat that builds leg power and conditioning.",
      "Squat down, jump up explosively, land softly on bent knees, and go straight into the next rep.",
      timed=True),
]
